name: Plinko Documentation
run-name: Generating Plinko documentation
on: [push]
jobs:
  Generate-Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          command: go run cmd/example/main.go
